const players = [
    'Shauna Summers',
    'Lacey Perry',
    'Gustavo Bolton',
    'Janette Santiago',
    'Hector Blair',
    'Erna Haas',
    'Sophie Henry',
    'Lisa Payne',
    'Priscilla Herring',
    'Janine Craig',
    'Jimmie Estes',
    'Valarie Schmitt',
    'Cornelius Gallegos',
    'Lelia Cortez',
    'Mckinley Sparks',
    'Julie Cooley',
    'Dorsey Kerr',
    'Prince Dunn',
    'Wilton Fischer',
    'Cole Garrett',
    'Luciano Stevens',
    'Janet Zimmerman',
    'Keri Black',
    'Robbie Brooks',
    'Bernardo Koch',
]

export default players